name: Deploy to Server

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.7.0
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
  
    - name: Add server to known hosts
      run: |
        ssh-keyscan -H 34.207.140.240 >> ~/.ssh/known_hosts

    - name: Deploy to Server
      run: |
        rsync -avz --delete ./ ubuntu@34.207.140.240:/home/ubuntu/node-js-dummy-test
        ssh ubuntu@34.207.140.240 'sudo systemctl restart nginx'
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
