name: Deploy to Server

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.7.0
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Deploy to Server
      run: |
        
        ssh -o StrictHostKeyChecking=no ubuntu@34.207.140.240 << 'ENDSSH'
          # Navigate to the deployment directory
          exec > >( tee -a "/home/ubuntu/gitlog.log" ) 2>&1
          export PATH=$PATH:/home/ubuntu/.nvm/versions/node/v20.10.0/bin
          cd /home/ubuntu/deploys/node-js-dummy-test 
          
          
          git pull origin master

     
          npm install

          pm2 restart all

         
          sudo systemctl restart nginx
        ENDSSH
        
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
